# Generated by Django 4.2.29 on 2026-03-19 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('natural_language', models.TextField()),
                ('generated_sql', models.TextField()),
                ('executed_sql', models.TextField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'query_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
